kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-roboshop
provisioner: efs.csi.aws.com
reclaimPolicy: Retain 
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-92107410 # replace with your file-system id
  directoryPerms: "700"
  basePath: "/roboshop" # optional
  