apiVersion: v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    purpose: rs-demo
    project: roboshop
    environment: dev
spec:
  replicas: 2
  matchLables:
    purpose: rs-demo
    project: roboshop
    environment: dev
  template:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
    